excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://MarceloH.github.io
title: Marcelo Himura
tagline: A log of everyday life
description: Ⓜarcelo Hernane - Gerente de projetos - Músico por hobby Contato:hernane.analista@gmail.com
paginate: 5
