excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://MarceloH.github.io
title: Ⓜarcelo
tagline: A log of everyday life
description: Every day is a new beginming take a deep breath and start again 😉😌
paginate: 5
